/**自定义模块，定义页面参数转换模块*/
layui.define(['layer'], function (exports) {
    var params = {
       SEX_LIST:[
	      {value:'M',name:'男'},
	      {value:'F',name:'女'},
       ],
       USER_STATUS:[
	      {value:'0',name:'正常'},
	      {value:'1',name:'暂时冻结'},
	      {value:'2',name:'用户停用'},
	      {value:'3',name:'永久冻结'},
       ],
       BRANCH_TYPE:[
            {value:'0',name:'超级机构'},
			{value:'1',name:'部门机构'},
			{value:'2',name:'项目机构'},
			{value:'3',name:'应用机构'},
			{value:'4',name:'团队机构'},
       ],
       ROLE_TYPE:[
	        {value:'0',name:'超级角色'},
			{value:'1',name:'部门角色'},
			{value:'2',name:'项目角色'},
			{value:'3',name:'应用角色'},
			{value:'4',name:'团队角色'},
       ],
      APP_FRAMETYPE:[
        {value:'OT',name:'其他'},
        {value:'EMP',name:'EMP'},
        {value:'IFP2.0',name:'IFP2.0'}
      ],
      MSG_TYPE:[
        {value:'J',name:'JSON报文'},
        {value:'X',name:'XML报文'},
        {value:'F',name:'定长报文'},
        {value:'K',name:'表单提交'},
        {value:'I',name:'8583报文'}
      ],
      REQ_TYPE:[
        {value:'POST',name:'POST'},
        {value:'GET',name:'GET'}
      ],
      REQ_METHOD:[
         {value:'HTTP',name:'HTTP'},
         {value:'HTTPS',name:'HTTPS'},
         {value:'TCP/IP',name:'TCP/IP'}
      ],
      INT_TYPE:[
         {value:'I',name:'对内接口'},
         {value:'O',name:'对外接口'},
         {value:'A',name:'内外接口'}
      ],
      INT_STATUS:[
          {value:'Y',name:'已投产'},
          {value:'N',name:'未投产'},
      ],
      YES_NO:[
                  {value:'Y',name:'是'},
                  {value:'N',name:'否'},
      ],
      OS_TYPE:[
         {value:'Window',name:'Window'},
         {value:'Linux',name:'Linux'}
      ],
      ENCODE_LIST:[
         {value:'UTF-8',name:'UTF-8'},
         {value:'GBK',name:'GBK'},
         {value:'ISO-8859-1',name:'ISO-8859-1'}
      ],
      DRIVER_LIST:[
        {value:'DB2',name:'com.ibm.db2.jcc.DB2Driver'},
        {value:'MySql',name:'com.mysql.jdbc.Driver'},
        {value:'Oracle',name:'oracle.jdbc.driver.OracleDriver'},
        {value:'SqlServer',name:'com.microsoft.jdbc.sqlserver.SQLServerDriver'},
      ],
      DATABASE_TYPE:[
         {value:'DB2',name:'DB2'},
         {value:'MySql',name:'MySql'},
         {value:'Oracle',name:'Oracle'},
         {value:'SqlServer',name:'SqlServer'}
      ],
      DBURL_HEAD:[
         {value:'DB2',name:'jdbc:db2://'},
         {value:'MySql',name:'jdbc:mysql://'},
         {value:'Oracle',name:'jdbc:oracle:thin:@'},
         {value:'SqlServer',name:'jdbc:microsoft:sqlserver://'},
      ],
      TEST_STATUES:[
                  {value:'0',name:'案列问题'},
                  {value:'1',name:'环境问题'},
                  {value:'2',name:'程序问题'}
               ],
      SERVICE_TYPE:[
			{value:'S',name:'查询类'},
			{value:'A',name:'新增类'},
			{value:'M',name:'修改类'},
			{value:'D',name:'删除类'},
			{value:'T',name:'交易类'},
      ],
      VALUE_TYPE:[
          {value:'S',name:'字符'},
          {value:'N',name:'数字'},
          {value:'B',name:'字节'}
      ],
      FIELD_POSITION:[
          {value:'RH',name:'请求报文头'},
          {value:'RB',name:'请求报文体'},
          {value:'PH',name:'响应报文头'},
          {value:'PB',name:'响应报文体'}
      ],
      FIELD_AREA:[
          {value:'RH',name:'报文头'},
          {value:'RB',name:'报文体'}
      ],
      FIELD_TYPE:[
          {value:'M',name:'必填'},
          {value:'C',name:'有条件必填'},
          {value:'O',name:'选填'}
      ],
      DATA_TYPE:[
          {value:'V',name:'value'},
          {value:'M',name:'Map'},
          {value:'L',name:'List'}
      ],
      TEST_TYPE:[
                  {value:'90',name:'成功'},
                  {value:'99',name:'失败'}                 
              ]
      ,BATCH_FLOW_STATUS:[
          {value:'0',name:'待跑批'},            
          {value:'1',name:'跑批中'},            
          {value:'2',name:'已跑批'}           
      ]
    ,BATCH_FLOW_TYPE:[
        {value:'A',name:'自动发起'},            
        {value:'P',name:'个人发起'}           
        ],
     SCRTPT_TYPE:[
        {value:'B',name:'前置脚本'},
        {value:'A',name:'后置脚本'},
        {value:'C',name:'检查脚本'}
     ],
     VALUE_CODE:[
       {value:'@getFlowNo',name:'随机流水'},
       {value:'@getTime',name:'系统日期'}
     ],
     RSP_FORMAT:[
       {value:'com.ycnet.comm.document.CommDocument',name:'com.ycnet.comm.document.CommDocument'},
       {value:'com.ycnet.comm.document.JSONDocument',name:'com.ycnet.comm.document.JSONDocument'},
       {value:'com.ycnet.comm.document.YqInterfaceDocument',name:'com.ycnet.comm.document.YqInterfaceDocument'},
       {value:'com.ycnet.comm.document.SplitSoapDocument',name:'com.ycnet.comm.document.SplitSoapDocument'}
     ],
     HTTP_CLIENT:[
        {value:'com.ycnet.connector.comm.http.DynamicHttpClient',name:'com.ycnet.connector.comm.http.DynamicHttpClient'}
     ]
    };
    exports('params', params);
});